// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Nl3OZobGOTye4imz4VIDG2OdrDiYOxc',
    appId: '1:373803406503:web:3c9d0100da26e958323782',
    messagingSenderId: '373803406503',
    projectId: 'fir-flutter-codelab-5d2cb',
    authDomain: 'fir-flutter-codelab-5d2cb.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5d2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmIbqQo6kDbAQ4w4pB37-f8HDN5xomdA',
    appId: '1:373803406503:ios:f86acec044caaaa5323782',
    messagingSenderId: '373803406503',
    projectId: 'fir-flutter-codelab-5d2cb',
    storageBucket: 'fir-flutter-codelab-5d2cb.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmIbqQo6kDbAQ4w4pB37-f8HDN5xomdA',
    appId: '1:373803406503:ios:f86acec044caaaa5323782',
    messagingSenderId: '373803406503',
    projectId: 'fir-flutter-codelab-5d2cb',
    storageBucket: 'fir-flutter-codelab-5d2cb.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
